Clean up displaying errors when fetching build scans
Previously, if a build scan failed to fetch, then the error would be printed on
the same line as the "Fetching build scan data" line, which was messy and
harder to read. Now, error messages are gaurenteed to be on their own newline.

Before:

```
Fetching build scan dataERROR: Failed to authenticate while attempting to fetch build scan https://example.com/s/jfg3vjxcgr3t2.
ERROR: Failed to authenticate while attempting to fetch build scan https://example.com/s/wn43gciypu5j4.
, done.
```

After:

```
Fetching build scan data
ERROR: Failed to authenticate while attempting to fetch build scan https://example.com/s/sn6yisoolyoeu.
ERROR: Failed to authenticate while attempting to fetch build scan https://example.com/s/v4q6wqny4rvvm.
done.
```